name       : python-qt5
version    : 5.10.1
release    : 19
source     :
    - https://jaist.dl.sourceforge.net/project/pyqt/PyQt5/PyQt-5.10.1/PyQt5_gpl-5.10.1.tar.gz : 9932e971e825ece4ea08f84ad95017837fa8f3f29c6b0496985fa1093661e9ef
license    : GPL-3.0
component  : programming.python
summary    : python-qt5 are the python2 bindings for Qt5.
description: |
    python-qt5 are the python2 bindings for Qt5.
builddeps  :
    - pkgconfig(dbus-python)
    - pkgconfig(gl)
    - pkgconfig(Qt5Bluetooth)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5XmlPatterns)
    - python-sip-devel
rundeps    :
    - python-sip
setup      : |
    %apply_patches

    python2 configure.py --confirm-license \
        --no-sip-files \
        --qsci-api \
        -q /usr/bin/qmake \
        QMAKE_CFLAGS_RELEASE="$CFLAGS" \
        QMAKE_CXXFLAGS_RELEASE="$CXXFLAGS" \
        QMAKE_LFLAGS_RELEASE="$LDFLAGS"
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
    install -d $installdir/usr/share/sip/PyQt5
    cp -r sip/* $installdir/usr/share/sip/PyQt5
    mv $installdir/usr/bin/{,python2-}pyuic5
