name       : python-qt5
version    : 5.14.2
release    : 33
source     :
    - https://pypi.python.org/packages/source/P/PyQt5/PyQt5-5.14.2.tar.gz : bd230c6fd699eabf1ceb51e13a8b79b74c00a80272c622427b80141a22269eb0
license    : GPL-3.0-or-later
component  : programming.python
summary    : python-qt5 are the python2 bindings for Qt5
description: |
    python-qt5 are the python2 bindings for Qt5.
builddeps  :
    - pkgconfig(Qt5Bluetooth)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(x11)
    - pkgconfig(dbus-python)
    - python-enum34
    - python-sip-devel
rundeps    :
    - python-sip
setup      : |
    python2 configure.py --confirm-license \
        --no-sip-files \
        --qsci-api \
        -q /usr/bin/qmake \
        QMAKE_CFLAGS_RELEASE="$CFLAGS" \
        QMAKE_CXXFLAGS_RELEASE="$CXXFLAGS" \
        QMAKE_LFLAGS_RELEASE="$LDFLAGS"
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir" -j1
    install -d $installdir/usr/share/sip/PyQt5
    cp -a sip/* $installdir/usr/share/sip/PyQt5
    mv $installdir/usr/bin/{,python2-}pyuic5
