name       : python-qt5
version    : 4.11.4
release    : 1
source     :
    - http://downloads.sourceforge.net/project/pyqt/PyQt4/PyQt-4.11.4/PyQt-x11-gpl-4.11.4.tar.gz : fc1fe77495432ba3b0d74ff5cb164d375a97f5dddb728256330f615a7cdcf407
license    : GPL-3.0
summary    : python-qt5 are the python2 bindings for Qt5.
description: |
    python-qt5 are the python2 bindings for Qt5.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(Qt5Core)
    - python3-dbus
    - python-sip-devel
setup      : |
    python2 configure-ng.py --confirm-license --no-sip-files --qsci-api -q /usr/bin/qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
