name       : python-qt5
version    : 5.8.2
release    : 11
source     :
    - https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.8.2/PyQt5_gpl-5.8.2.tar.gz : ebd70515b30bbd6098fee29e6271a6696b1183c5530ee30e6ba9aaab195536e8
license    : GPL-3.0
component  : programming.python
summary    : python-qt5 are the python2 bindings for Qt5.
description: |
    python-qt5 are the python2 bindings for Qt5.
builddeps  :
    - pkgconfig(dbus-python)
    - pkgconfig(gl)
    - pkgconfig(python-2.7)
    - pkgconfig(Qt5Bluetooth)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Location)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5XmlPatterns)
    - python-sip-devel
rundeps    :
    - python-sip
setup      : |
    python2 configure.py --confirm-license --no-sip-files --qsci-api -q /usr/bin/qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
    install -d $installdir/usr/share/sip/PyQt5
    cp -r sip/* $installdir/usr/share/sip/PyQt5
    mv $installdir/usr/bin/{,python2-}pyuic5
